{
 "title": "Hubitat Evolution Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU % ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpuPct",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "Hubitat" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "Hubitat" }
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freeMemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "Hubitat" }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Percent Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_hub",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hub" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "hubcpuPct",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpuPct",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hub Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_hub",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceId" ], "type": "tag" },
      { "params": [ "hub" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "hubTemp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=", "value": "Hub Temperature" },
      { "condition": "AND", "key": "hub", "operator": "=", "value": "Hubitat" },
      { "condition": "OR", "key": "hub", "operator": "=", "value": "Hubitat - C4" },
      { "condition": "OR", "key": "displayName", "operator": "=", "value": "Hub Temperature" },
      { "condition": "AND", "key": "hub", "operator": "=", "value": "HubitatDev" }
     ]
    },
    {
     "alias": "$tag_hubName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hubName::tag" ], "type": "tag" },
      { "params": [ "hub::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "HubitatDev" }
     ]
    },
    {
     "alias": "Hubitat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName::tag" ], "type": "tag" },
      { "params": [ "hub::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "Hubitat" }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_hub",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hub" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "hubDbSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "dbSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_hub",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hub" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "responseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hubitat Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_hub",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hub" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "freeMem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "freeMemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}