{
 "title": "HVAC Activity SQL",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "tagName", "label": "Tag Name", "query": "deviceName, displayName" },
   {
    "name": "thermostat",
    "label": "Thermostat",
    "query": {
     "query": "SELECT \"deviceName\" FROM 'thermostatOperatingState' WHERE time >= now() - interval '7 days' group by \"deviceName\""
    }
   },
   {
    "name": "hvac_temp_Sensors",
    "label": "HVAC Temp Sensors",
    "query": {
     "query": "SELECT \"deviceName\" FROM temperature WHERE time >= now() - interval '7 days' group by \"deviceName\" order by \"deviceName\" desc"
    }
   },
   {
    "name": "outdoor_Temp_Sensors",
    "label": "Outdoor Sensors",
    "query": {
     "query": "SELECT \"deviceName\" FROM temperature WHERE time >= now() - interval '7 days' group by \"deviceName\" order by \"deviceName\" desc"
    }
   },
   {
    "name": "indoor_temp_Sensors",
    "label": "Indoor Sensors",
    "query": {
     "query": "SELECT \"deviceName\" FROM temperature WHERE time >= now() - interval '7 days' group by \"deviceName\" order by \"deviceName\" desc\n"
    }
   },
   {
    "name": "outdoor_AQ_Sensors",
    "label": "Outdoor AQ Sensors",
    "query": {
     "query": "SELECT \"deviceName\" FROM temperature WHERE time >= now() - interval '7 days' group by \"deviceName\" order by \"deviceName\" desc"
    }
   },
   {
    "name": "Indoor_AQ_Sensors",
    "label": "Indoor Air Quality Sensors",
    "query": {
     "query": "SELECT \"deviceName\" FROM temperature WHERE time >= now() - interval '7 days' group by \"deviceName\" order by \"deviceName\" desc"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HVAC Setpoint with Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  date_bin($__interval, \"time\") AS \"time\",\r\n  '[' || \"${tagName}\" || ']' AS \"field\", -- Replicates your custom bracketed name\r\n  \"value\" AS \"\",\r\n  \"measurement\"\r\nFROM (\r\n  SELECT *, 'coolingSetpoint' AS \"measurement\" FROM \"coolingSetpoint\"\r\n  UNION ALL\r\n  SELECT *, 'heatingSetpoint' AS \"measurement\" FROM \"heatingSetpoint\"\r\n)\r\nWHERE \r\n  \"time\" >= $__timeFrom - interval '1 day'\r\n  AND \"time\" <= $__timeTo\r\n  AND \"${tagName}\" ~ '^${thermostat:regex}$'\r\nGROUP BY 1, 2, 3, 4\r\nORDER BY \"time\" ASC"
    },
    {
     "dataset": "iox",
     "query": "import \"date\"\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"${tagName}\"] =~ /^${hvac_temp_Sensors:regex}$/)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _measurement:r._measurement, _field:\"[\"+r[\"${tagName}\"]+\"]\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT \r\n  date_bin($__interval, \"time\") AS \"time\",\r\n  \"${tagName}\" AS \"_tagName\", \r\n  AVG(\"value\") AS \"_value\"\r\nFROM \"temperature\"\r\nWHERE \r\n  \"time\" >= $__timeFrom\r\n  AND \"time\" <= $__timeTo\r\n  AND \"${tagName}\" ~ '^${hvac_temp_Sensors:regex}$'\r\nGROUP BY 1, 2\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Operating State",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  \"state\",\r\n  SUM(\"duration_seconds\")  AS \"total_hours\" -- Converts seconds to decimal hours\r\nFROM (\r\n  SELECT \r\n    \"value\" AS \"state\",\r\n    \"time\",\r\n    -- Calculate the difference between this event and the next one in seconds\r\n    extract(epoch from (LEAD(\"time\") OVER (PARTITION BY \"${tagName}\" ORDER BY \"time\" ASC) - \"time\")) AS \"duration_seconds\"\r\n  FROM \"thermostatOperatingState\"\r\n  WHERE \r\n    \"time\" >= $__timeFrom\r\n    AND \"time\" <= $__timeTo\r\n    AND \"${tagName}\" ~ '^${thermostat:regex}$'\r\n)\r\nWHERE \"duration_seconds\" IS NOT NULL -- Drops the very last point which has no 'next' time\r\nGROUP BY \"state\"\r\nORDER BY \"total_hours\" DESC"
    }
   ]
  },
  {
   "title": "HVAC Operating State",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "iox",
     "query": "\r\n",
     "rawSql": "SELECT \r\n  \"time\",\r\n  \"${tagName}\" AS \"metric\", \r\n  \"value\" as \"\"\r\nFROM \"thermostatOperatingState\"\r\nWHERE \r\n  \"time\" >= $__timeFrom - interval '1 day'\r\n  AND \"time\" <= $__timeTo\r\n  AND \"${tagName}\" ~ '^${thermostat:regex}$'\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Outdoor Temp Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  date_bin($__interval, \"time\") AS \"time\",\r\n  \"${tagName}\" AS \"device_name\", \r\n  AVG(\"value\") AS \"\"\r\nFROM \"temperature\"\r\nWHERE \r\n  \"time\" >= $__timeFrom\r\n  AND \"time\" <= $__timeTo\r\n  AND \"${tagName}\" ~ '^${outdoor_Temp_Sensors:regex}$'\r\nGROUP BY 1, 2\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Indoor Temp Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"${tagName}\"] =~ /^${indoor_temp_Sensors:regex}$/)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _measurement:r[\"${tagName}\"]}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  ",
     "rawSql": "SELECT \r\n  date_bin($__interval, \"time\") AS \"time\",\r\n  \"${tagName}\" AS \"device_name\", \r\n  AVG(\"value\") AS \"\"\r\nFROM \"temperature\"\r\nWHERE \r\n  \"time\" >= $__timeFrom\r\n  AND \"time\" <= $__timeTo\r\n  AND \"${tagName}\" ~ '^${indoor_temp_Sensors:regex}$'\r\nGROUP BY 1, 2\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "HVAC Temp Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  date_bin($__interval, \"time\") AS \"time\",\r\n  \"${tagName}\" AS \"device_name\", \r\n  AVG(\"value\") AS \"\"\r\nFROM \"temperature\"\r\nWHERE \r\n  \"time\" >= $__timeFrom\r\n  AND \"time\" <= $__timeTo\r\n  AND \"${tagName}\" ~ '^${hvac_temp_Sensors:regex}$'\r\nGROUP BY 1, 2\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Indoor Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"CO2\",\r\n  \"${tagName}\" AS metric\r\nFROM \"carbonDioxide\"\r\nWHERE\r\n  $__timeFilter(time)\r\n  AND \"${tagName}\" ~ '^${Indoor_AQ_Sensors:regex}$'\r\n ORDER by time ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"TVOC\",\r\n  \"${tagName}\" AS metric\r\nFROM \"tvoc\"\r\nWHERE\r\n  $__timeFilter(time)\r\n  AND \"${tagName}\" ~ '^${Indoor_AQ_Sensors:regex}$'\r\n ORDER by time ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"pm25\",\r\n  \"${tagName}\" AS metric\r\nFROM \"pm25\"\r\nWHERE\r\n  $__timeFilter(time)\r\n  AND \"${tagName}\" ~ '^${Indoor_AQ_Sensors:regex}$'\r\n ORDER by time ASC"
    }
   ]
  },
  {
   "title": "Outdoor Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"pm25\",\r\n  \"${tagName}\" AS metric\r\nFROM \"pm25\"\r\nWHERE\r\n  $__timeFilter(time)\r\n  AND \"${tagName}\" ~ '^${outdoor_AQ_Sensors:regex}$'\r\n ORDER by time ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"temperature\",\r\n  \"${tagName}\" AS metric\r\nFROM \"temperature\"\r\nWHERE\r\n  $__timeFilter(time)\r\n  AND \"${tagName}\" ~ '^${outdoor_AQ_Sensors:regex}$'\r\n ORDER by time ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"humidity\",\r\n  \"${tagName}\" AS metric\r\nFROM \"humidity\"\r\nWHERE\r\n  $__timeFilter(time)\r\n  AND \"${tagName}\" ~ '^${outdoor_AQ_Sensors:regex}$'\r\n ORDER by time ASC"
    }
   ]
  }
 ]
}