{
 "title": "Sensors SQL",
 "time": { "from": "now-5d", "to": "now" },
 "templating": {
  "list": [
   { "name": "tagName", "label": "Tag Name", "query": "deviceName, displayName" },
   {
    "name": "tempSensors",
    "label": "Temperature",
    "query": {
     "query": "SELECT DISTINCT \"${tagName}\" FROM \"temperature\" \n WHERE time >= $__timeFrom() \nUNION\nSELECT DISTINCT \"${tagName}\" FROM \"humidity\" \nWHERE \"time\" >= '${__from:date:iso}' AND \"time\" <= '${__to:date:iso}'\nORDER BY 1 ASC\n"
    }
   },
   {
    "name": "battery",
    "label": "Battery",
    "query": {
     "query": "SELECT DISTINCT \"deviceName\" FROM 'battery'  WHERE time >= $__timeFrom() "
    }
   },
   {
    "name": "onOffSensors",
    "label": "Motion | Contact | Presence",
    "query": {
     "query": "SELECT \"deviceName\" FROM motion WHERE time >= $__timeFrom() \nUNION\nSELECT \"deviceName\" FROM contact WHERE time >= $__timeFrom() \nUNION\nSELECT \"deviceName\" FROM presence WHERE time >= $__timeFrom() "
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"temperature\"\nWHERE\n  $__timeFilter(time)\n  AND temperature.\"${tagName}\" ~ '^${tempSensors:regex}$'\n ORDER by time ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"temperature\"\nWHERE\n  $__timeFilter(time)\n  AND temperature.\"${tagName}\" ~ '^${tempSensors:regex}$'\n ORDER by time ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"humidity\"\nWHERE\n  $__timeFilter(time)\n  AND humidity.\"${tagName}\" ~ '^${tempSensors:regex}$'\n ORDER by time ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"humidity\"\nWHERE\n  $__timeFilter(time)\n  AND humidity.\"${tagName}\" ~ '^${tempSensors:regex}$'\n ORDER by time ASC"
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery",
     "rawSql": "SELECT \n  date_bin(interval '1 day', \"time\") AS \"time\", \n  \"${tagName}\" AS \"name\", \n  \"value\" as \"\"\nFROM (\n  SELECT \n    *,\n    ROW_NUMBER() OVER (PARTITION BY \"${tagName}\" ORDER BY \"time\" DESC) as row_num\n  FROM \"battery\"\n  WHERE \n    \"time\" >= now() - interval '1 day'\n    -- FIX: Use = with :sqlstring instead of regex\n    AND \"${tagName}\" in (${battery:sqlstring})\n)\nWHERE row_num = 1\nORDER BY \"time\" ASC, \"value\" ASC\n"
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "\r\n  ",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"battery\"\nWHERE\n  $__timeFilter(time)\n  AND \"${tagName}\" IN (${battery:sqlstring})\n ORDER by time ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "  from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r._value < 160)\r\n  |> filter(fn: (r) => r[\"${tagName}\"] =~ /^${tempSensors:regex}$/)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _measurement:r[\"${tagName}\"]}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"temperature\"\nWHERE\n  $__timeFilter(time)\n ORDER by time ASC"
    }
   ]
  },
  { "title": "Historical M/C/P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Motion | Contact | Presence",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "\r\n",
     "rawSql": "SELECT \n  \"time\",\n  \"${tagName}\" AS \"device\", \n  \"value\" as \"\"\nFROM (\n  SELECT \"time\", \"${tagName}\", \"value\" FROM \"motion\"\n  UNION ALL\n  SELECT \"time\", \"${tagName}\", \"value\" FROM \"presence\"\n  UNION ALL\n  SELECT \"time\", \"${tagName}\", \"value\" FROM \"contact\"\n)\nWHERE \n  \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\n  AND \"${tagName}\" ~ '^${onOffSensors:regex}$'\nORDER BY \"device\" asc, \"time\" ASC"
    }
   ]
  },
  { "title": "Historical Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"humidity\"\nWHERE\n  $__timeFilter(time)\n  AND humidity.\"${tagName}\" ~ '^${tempSensors:regex}$'\n ORDER by time ASC"
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery",
     "rawSql": "SELECT\n  time,\n  value as \"\",\n  \"${tagName}\" AS metric\nFROM \"battery\"\nWHERE\n  $__timeFilter(time)\n  AND \"${tagName}\" IN (${battery:sqlstring})\n ORDER by time ASC"
    }
   ]
  }
 ]
}